### PR TITLE
Fix handling of disabled recipes

### LINKED ISSUE #122: (Investigation) Why do recipes sometimes show up for disabled recipes and sometimes do not?
From https://github.com/have-fun-was-taken/yafc-ce/pull/121#issuecomment-2104416614

> One thing i noticed while investigating this:
> 
> Before when you disable a recipe, the item row is emptied. Old projects still have this state stored:
> 
> afbeelding
> 
> If i enable them now and disable again, i get the recipes visible: afbeelding
> 
> I'm not sure if this was intended, i tried to go to older versions along the master branch, but couldn't find any yet without this problem until i ran into the ones with the libf problem.

### PR DESCRIPTION
**Pull request by DaleStan**
As discussed briefly in #122, always show empty boxes for both the ingredients and products of disabled recipes. That is, they'll always look like this:
image

I also discovered the code that cleans up old links removes links if the item/fluid does not appear in any _enabled_ recipes. I wanted the links to stay put when disabling and enabling recipes, and I couldn't concentrate on #122 with that behavior, so I changed the code to consider all recipes. If that change (f28d35f) should be discussed more, I can remove it from this PR.

### CODE REVIEW

**Comment by Dorus** [comment]
> I also discovered the code that cleans up old links removes links if the item/fluid does not appear in any enabled recipes.

How so? It's not doing that for me in the master branch.

File: Yafc/Workspace/ProductionTable/ProductionTableView.cs [hunk 1]
```diff
@@ -401,8 +401,8 @@ private class IngredientsColumn(ProductionTableView view) : ProductionTableDataC
                 else {
                     for (int i = 0; i < recipe.recipe.ingredients.Length; i++) {
                         var ingredient = recipe.recipe.ingredients[i];
-                        var link = recipe.links.ingredients[i];
-                        var goods = recipe.links.ingredientGoods[i];
+                        var link = recipe.hierarchyEnabled ? recipe.links.ingredients[i] : null;
+                        var goods = recipe.hierarchyEnabled ? ingredient.goods : null;
```
Comment (have-fun-was-taken) [inline Yafc/Workspace/ProductionTable/ProductionTableView.cs:405]: If that's okay with you, please add documentation to the fields `RecipeRow.enabled` and `RecipeRow.hierarchyEnabled`, so the reader can understand the difference between them without browsing their usage.

**Comment by DaleStan** [comment]
@Dorus It's more of a special case than I realized, but load this file, and disable and enable the small parts recipe. The links for bolts, copper cable, and iron gear wheel will get deleted.
[links.yafc.txt](https://github.com/have-fun-was-taken/yafc-ce/files/15311076/links.yafc.txt)

**Comment by have-fun-was-taken** [comment]
Will test it today after 11 hours.

**Review by veger — APPROVED** [review]
Code changes look good to me.

I tried running it and while there are not visible issues, I do not see any difference with master branch when disabling/enabling. I guess I do not fully understand what I should try... :disappointed:  But having the item icons hidden and the building/fuel icons visible looks good to me good.

**Review by have-fun-was-taken — APPROVED** [review]
